#!/bin/bash
# ContextGraph Quick Start Script for Linux
# Run this to get started immediately

set -e

echo "=============================================="
echo "🚀 ContextGraph - Quick Start"
echo "=============================================="
echo ""

# Check Python version
python3 --version

# Install dependencies if needed
echo ""
echo "📦 Checking dependencies..."
pip install -q -r requirements.txt 2>/dev/null || echo "Dependencies already installed"

# Show available commands
echo ""
echo "✅ Installation complete!"
echo ""
echo "=============================================="
echo "📖 HOW TO USE"
echo "=============================================="
echo ""
echo "1. START WATCHING YOUR CODE (Real-time sync):"
echo "   python3 -c \""
echo "   from contextgraph.sync_engine import RealTimeSyncEngine"
echo "   engine = RealTimeSyncEngine('.', 'my-project')"
echo "   engine.start_watching()"
echo "   print('Watching for file changes... Press Ctrl+C to stop')"
echo "   import time"
echo "   while True: time.sleep(1)"
echo "   \""
echo ""
echo "2. CAPTURE AI INTERACTIONS:"
echo "   python3 -c \""
echo "   from contextgraph.sync_engine import capture_ai, export_compact"
echo "   capture_ai('Your question', 'AI response', 'gpt-4')"
echo "   print(export_compact())"
echo "   \""
echo ""
echo "3. CLI COMMANDS:"
echo "   cg init --name myproject"
echo "   cg add \"My project description\" --category project"
echo "   cg link \"concept1\" \"concept2\" related_to"
echo "   cg export"
echo "   cg status"
echo ""
echo "4. START API SERVER:"
echo "   cg serve --host 0.0.0.0 --port 8000"
echo ""
echo "5. READ DOCUMENTATION:"
echo "   cat README.md"
echo "   cat REALTIME_SYNC_GUIDE.md"
echo ""
echo "=============================================="
echo "💡 EXAMPLE WORKFLOW"
echo "=============================================="
echo ""
echo "# Step 1: Initialize and start watching"
echo "cg init --name my-coding-session"
echo ""
echo "# Step 2: Work on your code (auto-indexed!)"
echo "# Edit any .py, .js, .ts files in the background"
echo ""
echo "# Step 3: Ask an AI for help and capture it"
echo "python3 -c \"from contextgraph.sync_engine import capture_ai; capture_ai('How to optimize this function?', 'Use memoization...', 'claude-3')\""
echo ""
echo "# Step 4: Export when switching AI models"
echo "cg export > context_backup.txt"
echo ""
echo "# Step 5: Paste context_backup.txt content into ANY AI model"
echo ""
echo "=============================================="
echo "🎯 YOU'RE READY!"
echo "=============================================="
echo ""
echo "For enterprise features and deployment guides:"
echo "  → Read REALTIME_SYNC_GUIDE.md"
echo "  → Check STARTUP_KIT.md for business info"
echo ""
